CREATE TABLE PUBLIC.users(
user_id SERIAL NOT NULL,
username CHARACTER VARYING(50) NOT NULL,
first_name CHARACTER VARYING(50) NOT NULL,
last_name CHARACTER VARYING(50) NOT NULL,
password CHARACTER VARYING(50) NOT NULL,

CONSTRAINT user_id_pk PRIMARY KEY(user_id)
);