CREATE TABLE IF NOT EXISTS PUBLIC.GULFNET_TMT_USER(
    ID UUID NOT NULL DEFAULT UUID_GENERATE_V4(),
    DATE_CREATED TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CREATED_BY CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    DATE_UPDATED TIMESTAMP WITHOUT TIME ZONE ,
    UPDATED_BY CHARACTER VARYING COLLATE pg_catalog."default" ,
    USER_NAME CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    PASSWORD CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    FIRST_NAME CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    LAST_NAME CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    PHONE CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    EMAIL CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    LANGUAGE_PREFERENCE CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    STATUS CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    PROFILE_PHOTO CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT USER_ID_PK PRIMARY KEY(ID),
    CONSTRAINT USERNAME_UNQ UNIQUE (USER_NAME)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USER_ROLE(
    ID UUID NOT NULL DEFAULT UUID_GENERATE_V4(),
    DATE_CREATED TIMESTAMP WITHOUT TIME ZONE,
    CREATED_BY CHARACTER VARYING COLLATE pg_catalog."default",
    DATE_UPDATED TIMESTAMP WITHOUT TIME ZONE ,
    UPDATED_BY CHARACTER VARYING COLLATE pg_catalog."default" ,
    ROLE_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    CONSTRAINT USER_ROLE_ID_PK PRIMARY KEY(ID),
    CONSTRAINT ROLE_ID_FK FOREIGN KEY (ROLE_ID) REFERENCES PUBLIC.APP_ROLE (ID) MATCH SIMPLE,
    CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.GULFNET_TMT_USER (ID) MATCH SIMPLE
);

CREATE TABLE IF NOT EXISTS PUBLIC.LOGIN_AUDIT(
    ID UUID NOT NULL DEFAULT UUID_GENERATE_V4(),
    DATE_CREATED TIMESTAMP WITHOUT TIME ZONE,
    CREATED_BY CHARACTER VARYING COLLATE pg_catalog."default",
    DATE_UPDATED TIMESTAMP WITHOUT TIME ZONE ,
    UPDATED_BY CHARACTER VARYING COLLATE pg_catalog."default",
    USER_ID UUID NOT NULL,
    MACHINE_INFO CHARACTER VARYING COLLATE pg_catalog."default" ,
    LOCATION CHARACTER VARYING COLLATE pg_catalog."default" ,
    LOGIN_EXPIRY_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT LOGIN_AUDIT_ID_PK PRIMARY KEY(ID),
    CONSTRAINT LOGIN_AUDIT_ID_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.GULFNET_TMT_USER (ID) MATCH SIMPLE
);

CREATE TABLE IF NOT EXISTS PUBLIC.USER_PASSWORD_AUDIT(
    ID UUID NOT NULL DEFAULT UUID_GENERATE_V4(),
    DATE_CREATED TIMESTAMP WITHOUT TIME ZONE,
    CREATED_BY CHARACTER VARYING COLLATE pg_catalog."default",
    DATE_UPDATED TIMESTAMP WITHOUT TIME ZONE ,
    UPDATED_BY CHARACTER VARYING COLLATE pg_catalog."default" ,
    USER_ID UUID NOT NULL,
    ACTION CHARACTER VARYING COLLATE pg_catalog."default" ,
    OTP NUMERIC,
    OTP_EXPIRY_DATE TIMESTAMP WITHOUT TIME ZONE,
    STATUS CHARACTER VARYING COLLATE pg_catalog."default" ,
    CONSTRAINT USER_PASSWORD_ID_PK PRIMARY KEY(ID),
    CONSTRAINT USER_PASSWORD_ID_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.GULFNET_TMT_USER (ID) MATCH SIMPLE
);

CREATE TABLE IF NOT EXISTS PUBLIC.EMAIL_COMMUNICATION(
    ID UUID NOT NULL DEFAULT UUID_GENERATE_V4(),
    USER_ID UUID NOT NULL,
    ACTION CHARACTER VARYING COLLATE pg_catalog."default",
    EMAIL_STATUS CHARACTER VARYING COLLATE pg_catalog."default",
    CONSTRAINT EMAIL_COMMUNICATION_ID_PK PRIMARY KEY(ID),
    CONSTRAINT EMAIL_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.GULFNET_TMT_USER (ID) MATCH SIMPLE
);