
CREATE TABLE IF NOT EXISTS PUBLIC.USER_CONTACT(
    ID UUID NOT NULL DEFAULT UUID_GENERATE_V4(),
    DATE_CREATED TIMESTAMP WITHOUT TIME ZONE,
    CREATED_BY CHARACTER VARYING COLLATE pg_catalog."default",
    DATE_UPDATED TIMESTAMP WITHOUT TIME ZONE ,
    UPDATED_BY CHARACTER VARYING COLLATE pg_catalog."default" ,
    USER_CONTACT_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    CONSTRAINT USER_CONTACT_ID_PK PRIMARY KEY(ID),
    CONSTRAINT USER_CONTACT_ID_FK FOREIGN KEY (USER_CONTACT_ID) REFERENCES PUBLIC.GULFNET_TMT_USER (ID) MATCH SIMPLE,
    CONSTRAINT USER_ID_CONTACT_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.GULFNET_TMT_USER (ID) MATCH SIMPLE
);