CREATE TABLE IF NOT EXISTS PUBLIC.STAMP (
    ID UUID NOT NULL DEFAULT UUID_GENERATE_V4(),
    CREATED_ON TIMESTAMP WITHOUT TIME ZONE,
    CREATED_BY CHARACTER VARYING COLLATE pg_catalog."default",
    UPDATED_ON TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_BY CHARACTER VARYING COLLATE pg_catalog."default",
    STATUS CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    STAMP_FILE CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT STAMP_ID_PK PRIMARY KEY(ID)
);