
CREATE TABLE IF NOT EXISTS PUBLIC.USER_GROUP(
    ID UUID NOT NULL DEFAULT UUID_GENERATE_V4(),
    DATE_CREATED TIMESTAMP WITHOUT TIME ZONE,
    CREATED_BY CHARACTER VARYING COLLATE pg_catalog."default",
    DATE_UPDATED TIMESTAMP WITHOUT TIME ZONE ,
    UPDATED_BY CHARACTER VARYING COLLATE pg_catalog."default" ,
    GROUP_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    CONSTRAINT USER_GROUP_ID_PK PRIMARY KEY(ID),
    CONSTRAINT GROUP_ID_FK FOREIGN KEY (GROUP_ID) REFERENCES PUBLIC.ORG_GROUP (ID) MATCH SIMPLE,
    CONSTRAINT USER_GRP_ID_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.GULFNET_TMT_USER (ID) MATCH SIMPLE
);