CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS PUBLIC.APP_ROLE(
    ID UUID NOT NULL DEFAULT UUID_GENERATE_V4(),
    CODE CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    NAME CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ROLE_ID_PK PRIMARY KEY(ID),
    CONSTRAINT APP_ROLE_CODE_UNQ UNIQUE (CODE),
    CONSTRAINT APP_ROLE_NAME_UNQ UNIQUE (NAME)
);
