INSERT INTO APP_ROLE(CODE,NAME) VALUES ('ADMIN', 'Admin');
INSERT INTO APP_ROLE(CODE,NAME) VALUES ('MOBILE', 'Mobile');
INSERT INTO APP_ROLE(CODE,NAME) VALUES ('HQ', 'HQ');
INSERT INTO APP_ROLE(CODE,NAME) VALUES ('DELETE', 'Delete');