CREATE TABLE IF NOT EXISTS PUBLIC.SETTINGS (
    ID UUID NOT NULL DEFAULT UUID_GENERATE_V4(),
    CREATED_ON TIMESTAMP WITHOUT TIME ZONE,
    CREATED_BY CHARACTER VARYING COLLATE pg_catalog."default",
    UPDATED_ON TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_BY CHARACTER VARYING COLLATE pg_catalog."default",
    ORGANIZATION_CODE CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    ORGANIZATION_NAME CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    SUPPORT_URL CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    SUPPORT_EMAIL CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    SUPPORT_PHONE_NUMBER CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    LANGUAGE_PREFERENCE CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT SETTINGS_ID_PK PRIMARY KEY(ID)
);

INSERT INTO SETTINGS (
    ORGANIZATION_CODE,
    ORGANIZATION_NAME,
    SUPPORT_URL,
    SUPPORT_EMAIL,
    SUPPORT_PHONE_NUMBER,
    LANGUAGE_PREFERENCE
) VALUES (
    'JOSH',
    'JOSH SOFTWARE',
    'http://localhost:5433/josh',
    'josh.software@gmail.com',
    '9999999999',
    'ENGLISH'
);